name: Python CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout my project
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt
      - name: pylint
        run: |
          pylint $(git ls-files '*.py' ) --errors-only --disable=E0401
      - name: coverage
        run: |
          coverage run -m pytest
      - name: Reporting the coverage
        run: |
          coverage report
      - name : locust testing
        run: |
          uvicorn application.main:app &
          locust --config=tests/.locust.conf --locustfile=tests/locustfile.py --headless
      - name : Run code
        run: |
          python ../application/main2.py
